### PR TITLE
adapting to jupyterlab 3.0

### LINKED ISSUE #15: Theme does not support latest version of Jupyter Lab
```
ValueError: The extension "@yeebc/jupyterlab_neon_theme" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.3 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.2 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/apputils
```

My jupyter lab version is 3.0.5

### PR DESCRIPTION
**Pull request by myyc**
resolves #15. there's a bunch of stuff but most of it is boilerplate that i stole from the cookiecutter.

* extensions are now python packages (with boilerplate content, see `setup.py` and `jupyterlab_neon_theme/`)
* `package.json` uses `jlpm` which really is a wrapper to yarn.
* external fonts need to be handled specifically, check out `font.css` (added `base64-inline-loader` as a dev dependency: jupyterlab/jupyterlab#9839).

### CODE REVIEW

**Comment by yeebc** [comment]
Awesome! Thanks for your great work and solve the font issues.

**Comment by myyc** [comment]
check out if it installs cleanly? it worked fine with the new development procedure (`jupyter labextension develop --overwrite .`) but if i use `jupyter labextension link .` it throws webpack errors, which are fixed by moving `base64-inline-loader` to `dependencies` instead of `devDependencies`. not sure.

**Comment by yeebc** [comment]
Unfortunately I don't familar with webpack, but I think it should be put into `dependencies`. Because we also need `base64-inline-loader` to load fonts when running the theme, and the comand `jupyter labextension develop --overwrite .` will overwrite the styles of all themes.

**Comment by myyc** [comment]
sorry i didn't see this comment. it should be fine for a production setup (it installs cleanly from the extensions manager), let's see if anyone reports bugs.

**Comment by yeebc** [comment]
Yes, it only can be installed successfully from the extensions manager when put in the `dependencies`.

**Pull request merged**
